linux-system-roles/rhc

- meta/collection-requirements.yml
This file is used by tox-lsr to install collections automatically during test runs. Since we will need the `redhat_subscription` & the `rhsm_*` modules available in the `community.general` collection, add that collection to the `collection-requirements.yml` file.
Signed-off-by: Pino Toscano <ptoscano@redhat.com>
> meta: add `collection-requirements.yml`

- tests/tasks/setup_candlepin.yml
Properly checking that the SSL connection to Candlepin works requires also the CA of that Candlepin instance, which is generally not in the system CA store (but in /etc/rhsm/ca for subscription-manager).
Since this is only an existance check, disable the certificate validation. In case of SSL problems, the actual subscription-manager invocation will fail anyway.
> tests: always disable cert validation when checking Candlepin

- meta/main.yml
- tests/tasks/setup_candlepin.yml
- skip OSes not supported by Candlepin when deploying it
- claim to support EL7 and EL8 for now
> Improve OS support/checking

- tests/tasks/setup_candlepin.yml
This way it will be possible to use the test products available with the test data of the deployed Candlepin.
> tests: install some product certificates of deployed Candlepin

- README.md
The role uses the community.general collection, so describe this requirement in the `README.md` file, using a wording similar to what other roles in Linux System Roles have.
> README: describe community.general requirement

- tests/tasks/setup_candlepin.yml
When deploy Candlepin in the test system, tell it to also configure the repositories with test content for the test data (i.e. "-r" for the deploy script). This way it will be possible to simulate fetching actual content from it.
Fetch the GPG key for the repositories, so RPM can install the test packages.
> tests: enable content from deployed Candlepin

- .github/workflows/tox.yml
It seems to be currently failing, so pin tox-lsr to the last version before https://github.com/linux-system-roles/tox-lsr/pull/95
> ci: pin tox-lsr to version before ansible-core-2.14 addition

- README.md
- defaults/main.yml
- tasks/subscription-manager.yml
- tests/README.md
- tests/tasks/setup_candlepin.yml
Add a parameter for specifying the base URL for the content received from the subscription server.
This is set as separate parameter on its own, because the redhat_subscription module both configures it and passes it as argument to "subscription-manager register --baseurl"; the problem with `--baseurl` is that subscription-manager parses it and then assumes https as protocol, breaking the original URL set by the user.
Extend the test setup so it is possible to specify it.
> Implement rhc_baseurl

- tasks/subscription-manager.yml
Do not compare a string with an empty string, rather check it is not empty; fix an issue reported by yamllint.
Fixes commit 8ac253b971bb4544feb392ab0a1fc9289596bf38
Signed-off-by: Pino Toscano <ptoscano@redhat.com>
> Fix string checking

- tests/tasks/setup_candlepin.yml
When deploying Candlepin, copy the autogenerated CA certificate for Candlepin to the CA store of subscription-manager. This allows subscription-manager to validate the SSL connection to Candlepin, and thus there is no more need to set the connection as insecure.
> tests: install Candlepin CA cert for subscription-manager

- tasks/subscription-manager.yml
Since the default is null, then check for None or omit values before
checking whether it is undefined or an empty string.
Fix also the empty string check:
- remove the "default()" filter, as it should be defined as role
default variable
- cast it as string, so numbers will not cause the "length" filter to
bomb out
> Fix checks when setting rhsm.baseurl

- tests/tests_default.yml
By design, the role ensures that the system is subscribed by default; to subscribe an unsubscribed system credentials are needed (the "rhc_auth" parameters to the role), so if they are not passed the role will fail.
Add a basic test (without Candlepin) that checks for this situation.
> tests: add a failing tests_default

- tests/tasks/setup_candlepin.yml
`/etc/rhsm/ca` is created by `subscription-manager-rhsm-certificates`; on non-RHEL systems (Fedora, CentOS, etc),
`subscription-manager-rhsm-certificates` is not installed by default, and thus that directory does not exist. Since we want to copy certificates there, ensure it exists even before installing `subscription-manager-rhsm-certificates`.
Refactor/repurpose the existing task for that.
> tests: ensure `/etc/rhsm/ca` exists w/ deployed candlepin

- tasks/subscription-manager.yml
Older Ansible versions ships with those modules embedded, and thus will prefer them even when installing the `community.general` collection. Hence, qualify those modules, so we force their versions in `community.general`.
Thanks to Richard Megginson for the hint!
> Use FQCN for modules in community.general

- meta/collection-requirements.yml
The test infra does not support tests/collection-requirements.yml yet; hence, for now pull the extra collections needed for the tests as dependencies for the role.
> meta: temporarily add tests requirements for the role

- tests/tasks/setup_candlepin.yml
The self-signed certificate of Candlepin specifies the name, so using the IP address to connect causes the failure of the validation of the SSL connection.
> tests: refer to the local host using 'localhost'

- tasks/subscription-manager.yml
- tests/tests_release.yml
- tests/tests_repositories.yml
- vars/main.yml
The 'redhat_subscription' module currently requires parameters for credentials in case state=present. This applies also in case the system is already registered (and force_register=false), being then effectively unused. This is proposed as change to 'redhat_subscription' as: https://github.com/ansible-collections/community.general/pull/5664
In the meanwhile, workaround this situation locally in the role:
- add a fake credential string as private variable
- pass the fake credential string to both 'username' and 'password' in case rhc_state=present and the system is already registered
This way, all the users of the role do not need to specify credentials when not needed; this reflects in the tests, from which it is possible to drop the extra credentials.
> Workaround redhat_subscription requiring creds even when unneeded

- README.md
- defaults/main.yml
- tasks/subscription-manager.yml
- tests/README.md
- tests/tasks/setup_candlepin.yml
- tests/tasks/setup_squid.yml
- tests/tests_proxy.yml
- vars/main.yml
Add a parameter for configuring the proxy server used for connecting.
The syntax of the 'rhc_proxy' parameter is particular:
- 'rhc_proxy: {"state":"absent"}': resets the proxy configuration to
the default one (i.e. no proxy)
- if an attribute is not specified in 'rhc_proxy', then it is not
changed
- if an attribute is specified in 'rhc_proxy', then it is set to that
Because of this, there is some jinja gymnastic needed to all the
'server_proxy_*' parameters of the 'redhat_subscription' module to
either omit, set as empty (using a helper empty variable), or use the
passed value.
Make sure to test this:
- extend the test setup with variables related to unauthenticated,
authenticated, and non-working proxy servers
- add an helper script to deploy/configure squid in the test system;
having …
> Implement rhc_proxy

- tests/tests_repositories.yml
Followup of commit 1035e8da1a056996ab8fea2467dca9736eeb657e as additional credential previously needed (together with 'rhc_auth').
> tests: drop extra 'rhc_organization' parameter

- README.md
- defaults/main.yml
- tasks/check-insights-status.yml
- tasks/insights-client-unregistration.yml
- tasks/insights-client.yml
- tasks/main.yml
- tasks/set_vars.yml
- tests/tests_insights_client_register.yml
- tests/tests_proxy.yml
- tests/tests_release.yml
- tests/tests_repositories.yml
Add a minimal task to call "insights-client" via command module to register and unregister.
Extend the API with basic parameters:
- add "rhc_insights_state" for the registration of insights.
Add a very simple integration test that tries to register and unregister. Each step is done twice to verify the idempotency of the role on status changes.
Signed-off-by: Alba Hita Catala <ahitacat@redhat.com>
> Implement basic registration/unregistration

- .github/workflows/woke.yml
- tests/tasks/setup_candlepin.yml
Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
tests/tasks/setup_candlepin.yml - cleanup non-inclusive words.
> Add check for non-inclusive language

- README.md
- tasks/insights-client.yml
- tasks/main.yml
- tasks/set_vars.yml
- tasks/subscription-manager.yml
- tests/tasks/get_insights_uuid.yml
- tests/tasks/get_rhsm_uuid.yml
- tests/tests_insights_client_register.yml
- tests/tests_register_unregister.yml
- tests/tests_release.yml
Add an extra value to the `rhc_state` parameter to force the reconnection/registration of an already connected system, i.e. by disconnecting it first. When forcing the registration, some of the tasks/variables are used even if the system was previously connected (and thus its previous status does not matter).
In case we need to reconnect:
- avoid some checks on the status of subscription-manager or insights-client, as we will need to reconnect anyway, so unconditionally disconnect
- apply some of the logic/flows used for (not forced) connection
Make sure to test this:
- add helper scripts to get the system UUID from `subscription-manager`, and from `insights-client` (indirectly)
- extend `tests_register_unregister.yml`, and `tests_insights_client_register.yml` to get the rhsm/insights …
> Implement `rhc_state: reconnect`

- tests/tests_release.yml
Add missing disabling of Insights in few "rhc" usages in tests_release, so the test really does not try to register to Insights.
Followup of commit bdcb3250caa38166fca9c96e8099c71e9a2ebe8b.
`[citest skip]` because `tests/tests_release.yml` is not tested in CI (there are no releases available in the self-deployed Candlepin).
> tests: add missing "rhc_insights.state: absent" [citest skip]

- tests/tests_insights_client_register.yml
- tests/tests_proxy.yml
- tests/tests_register_unregister.yml
- tests/tests_release.yml
The role now may perform package checks in some cases, and because of that it needs to make sure that the package manager has usable repositories. Hence, pass the baseurl configured (if any, hence the "omit") for the tests as "rhc_baseurl" parameter in all the "rhc" invocations that are supposed to work (i.e. not fail for expected failing parameters).
> tests: specify "rhc_baseurl" where needed

- tests/tasks/setup_candlepin.yml
The right place for the product certificates used for content is `/etc/pki/product-default`, not `/etc/pki/product` -- the latter just happens to work fine because it's used by subscription-manager for certificates downloaded from the repositories.
There is no functional behaviour in the tests.
> tests: copy Candlepin product certs in the right place

- tests/tasks/setup_candlepin.yml
- tests/tasks/setup_squid.yml
Tweak the squid configuration to properly enforce authentication:
- disable the http_access bits that allow any localhost/localnet clients
- require authentication to connect
Also, tweak the test password for the proxy to be "proxypass" rather than "proxyuser" (which is the authentication username).
This affected only tests_proxy when run using a self-deployed Candlepin & squid; both the role and the test already worked fine, as testing against external servers (especially properly configured proxy servers) showed.
> tests: fix enforced squid authentication

- tests/tests_proxy.yml
- tests/tests_register_unregister.yml
In case we expect a task to fail, we check in the "rescue" part of a "block" that something actually failed; since the "block" has a "fail" task to force a failure in case the task did not fail, we want to check that the reason we get into "rescue" is not the "forced failure".
Hence, tighten the asserts to ignore the forced failure task. Suggested by Richard Megginson in
https://github.com/linux-system-roles/rhc/pull/48
> tests: improve assertions for negative tests

- tasks/subscription-manager.yml
- tests/README.md
- tests/tasks/setup_candlepin.yml
- tests/tests_register_unregister.yml
It seems that ".keys" for a dictionary is actually a reserved keyword, and thus it cannot be used; hence, use the array notation to look it up.
Also, auto-attach cannot be used when using activation keys, so do not enable it in that case.
Make sure to test this:
- extend the test data by adding all the pools for the "admin" user to the "default_key" (existing and with no pools), so auto-attach works
- add a simple test of registration with activation keys to tests_register_unregister
> Fix rhc_auth.activation_keys.keys

- tests/tasks/setup_candlepin.yml
'expect' is currently needed by the Candlepin script that generates and signs the test packages, so make sure it is installed.
This fixes the generation of the test RPM packages on EL7.
> tests: ensure 'expect' is installed for Candlepin

- tests/tests_release.yml
test release setting with force registration should have rhc_state: "reconnect" defined
Signed-off-by: Archana Pandey <arpandey@redhat.com>
> tests: fixed mising rhc_state parameter in release tests

- README.md
- defaults/main.yml
- tasks/insights-client.yml
- tests/tests_insights_client_register.yml
- tests/tests_insights_remediation.yml
- Add a new parameter `rhc_insights.remediation` to enable insights remediation.  This depends on additional packages that need to be installed and to enable and start a service.
- Add a configuration test that enables and disables remediation.
> Implement "rhc_insights.remediation"

- README.md
- defaults/main.yml
- tasks/subscription-manager.yml
- tests/README.md
- tests/tasks/list_environments.yml
- tests/tasks/setup_candlepin.yml
- tests/tests_environments.yml
Add a parameter for configuring the environments to register to when connecting (and only in that case, due to different permissions needed to change the environments in already connected systems).
Make sure to test this:
- extend the test setup with variables related to environments
- add an helper script to get the list of set environments from subscription-manager
- improve the Candlepin deployment by adding a couple of test environments
- add a new test to verify that setting environments on connection works
Since enabling environments makes the environment selection mandatory, pass the configured environments to all the invocations of "rhc" that actually do connect successfully.
> Implement rhc_environments

- meta/collection-requirements.yml
The test infra now supports tests/collection-requirements.yml; hence, revert the addition of the tests-only requirements from meta/collection-requirements.yml.
This reverts commit f311da4cdb1cf3b351307861bb7fcddd76a9de7e.
> Revert "meta: temporarily add tests requirements for the role (#20)"

- README.md
- defaults/main.yml
- tasks/insights-client.yml
- tests/tasks/get_insights_tags.yml
- tests/tests_insights_tags.yml
Add a new parameter to configure insights tags that will be added to the system record in HBI.
The syntax of this parameter is a dictionary, and the value for each key can be any data type.
The role will try to configure the tags if this parameter is present. If it is not present the tags will remain in the same status.
Test added that verifies:
- Add and delete tags
- Remove all tags
- Do not modify tags if the parameter is missing.
> Implemented "rhc_insights.tags" parameter

- meta/main.yml
After internal discussions, we decided to not support EL7 due to where it is in its lifecycle.
> meta: stop supporting EL7

- tests/tests_insights_tags.yml
Added a block and always section to unregister the system in case the test fails.
Disable remediation from the playbook to reduce the tasks done.
> Improve tests for insights tags

- tasks/insights-client.yml
- tasks/set_vars.yml
- tests/tests_insights_tags.yml
This tasks needs to check if the package is installed in the system before trying to disable it via systemd.
Added rhc_insights.remediation absent to one task of tags test that was missed to configure.
> Fix rhc_insights.remediation when absent

- tests/tasks/get_insights_tags.yml
- tests/tests_insights_tags.yml
Tests were taking the size of the file to compare but this was making the test to fail. This commit change how the size is compared.
> Fix insights_tags tests

- CHANGELOG.md
[1.1.0] - 2023-02-15
--------------------
- Implement "rhc_state: reconnect" (#43)
- Implement "rhc_insights.remediation"
- Implement rhc_environments (#48)
- rhc_repository: setting default state of repo to enabled (#65)
- Implemented "rhc_insights.tags" parameter
- meta: stop supporting EL7 (#66)
- Added "rhc_insights.autoupdate" parameter (#67)
- Fix rhc_auth.activation_keys.keys (#54)
- Fix rhc_insights.remediation when absent (#70)
- Add check for non-inclusive language
- ansible-lint 6.x fixes
Signed-off-by: Rich Megginson <rmeggins@redhat.com>
> Version 1.1.0 - CHANGELOG.md [citest skip]

- tests/files/candlepin_data.yml
- tests/tasks/check_candlepin.yml
- tests/tasks/setup_candlepin.yml
- tests/tasks/setup_test_data.yml
While the existing `setup_candlepin.yml` helper generally works fine, there are few drawbacks:
- in case we do not want to deploy Candlepin, the logic for reading the test data is duplicated in the tests
- in case a test is skipped because of a configuration in the test data of the deployed Candlepin, Candlepin will be deployed anyway
- because the test data of the deployed Candlepin is set after the deployment, all the data are manually set all over the place
To improve the situation, massage `setup_candlepin.yml` a bit:
- split the configuration of the deployed Candlepin in its own file (`candlepin_data.yml`)
- create `setup_test_data.yml`: this has the logic for importing the test data from an external file, or from `candlepin_data.yml`
- create `check_candlepin.yml`: small helper to …
> tests: refactor Candlepin setup

- tests/tests_release.yml
A local Candlepin deployment has no concept of "releases", so deploying it to unconditionally end the test is suboptimal.
Make use of the new helper tasks for the tests:
- only setup the test data first, so we get the configured release version for the test
- keep skipping the test if there is no configured release: this way, even an external Candlepin configuration may still skip the test
- ensure that the configured Candlepin works: `setup_candlepin.yml` does it automatically, so we need to manually use `check_candlepin.yml` now
The only behaviour change is that this test will end much faster when using the local Candlepin deployment (i.e. the default setup).
> tests: do not deploy Candlepin in tests_release

- tasks/check-insights-status.yml
- tasks/insights-client-unregistration.yml
- tasks/insights-client.yml
insights-client does not work properly when it is spawned from
/usr/bin/python, but it does work when spawned from /usr/bin/python3,
even if they are symlinks to each other i.e. the same binary.
Not sure why this is, but the workaround is to start
insights-client in the background and `wait` for it.
> workaround insights-client issue with /usr/bin/python

- tests/collection-requirements.yml
- tests/tests_proxy.yml
The test proxy uses non-standard ports which are not in the default
SELinux policy, so add them for the test, and remove them at the
end of the test.
> add and remove selinux ports for proxy access

- tests/README.md
- tests/files/candlepin_data.yml
- tests/tasks/setup_insights.yml
- tests/tests_insights_autoupdate.yml
- tests/tests_insights_client_register.yml
- tests/tests_insights_remediation.yml
- tests/tests_insights_tags.yml
Currently, the Insights-related tests assume they can work (as in, there is Insights support) when using an external test data configuration; this may not be true, e.g. when configuring to use a self-deployed Candlepin. Also, they all duplicate the logic for importing the test data.
Improve the situation a bit:
- add a `insights` boolean value for the test data to determine whether there is support for Insights; set it to false for the own Candlepin deployment
- create an helper `setup_insights.yml` to contain all the needed logic for setting up a test that uses Insights:
- only the test data is set up, as an own Candlepin does not support Insights
- end the play execution if the test data says there is no Insights support
- check that Candlepin works (it's needed in any case)
- use the …
> tests: refactor Insights setup

- tests/tasks/setup_candlepin.yml
The current way of deploying Candlepin uses an Ansible role that is no more used/supported by the Candlepin project, and thus it is rotting; the recent switch of Candlepin from Java 11 to Java 17 broke with the unmaintained role.
Thus, as very short-term workaround, pin the version of Candlepin to deploy to the commit before the switch to Java 17.
> tests: pin Candlepin version to latest before Java 17

- tasks/insights-client-unregistration.yml
- tasks/insights-client.yml
- tasks/main.yml
- mark tasks that run `insights-client` as `changed_when=true`: this is done because, when they run, they will change things in the system
- fix indentation of conditions in a couple of `when` blocks
> Fix minor ansible-lint issues

- tests/tasks/setup_squid.yml
Improve the configuration of squid, especially in the authenticated setup, to handle better also newer versions:
- reduce the shutdown lifetime to 5s (from the 30s default): this is the time squid will wait on shutdown for connections; since all the connections are local, we can afford waiting only few seconds
- add the Candlepin port right before the first `Safe_ports` line, rather than before the last (it should place it closer to the existing `SSL_ports`)
- keep `http_access deny all` when authenticated: this is needed to deny all the connections that do not match any `http_access` rule before this
- configure the authentication parameters at the beginning of the file, so they are usable also mid-file
- declare the `authenticated` acl right after the ports, together with other acl's
- …
> tests: update squid setup

- tests/tasks/setup_candlepin.yml
This way it is possible to validate the SSL connections to the locally deployed Candlepin.
> tests: install Candlepin certs in system CA store

- tasks/subscription-manager.yml
- tests/tests_register_unregister.yml
In case rhc_auth.activation_keys is specified (i.e. activation keys as credentials are used), then do not pass the fake username/password credentials to redhat_subscription, no matter the registration status; the redhat_subscription module rejects more than one credential type at the same time. This fixes specifying rhc_auth.activation_keys on an already registered system.
Check this case by duplicating the existing task for registration using activation keys in tests_register_unregister.yml, which now should pass (as noop) rather than failing.
Fixes #90
> Do not pass fake creds when activation keys are specified

- README.md
- tests/README.md
remove unused Dependencies section in README - it is confusing
to users who look at the README, see the `Dependencies` section
that says `None`, and think that there are no dependencies for
the role, when the actual dependencies are listed in the
`Requirements` section which is not even near the `Dependencies`
section.  So consistently use the `Requirements` section and
get rid of the `Dependencies` section.
In addition, for roles that use other system roles, they have a
`meta/collection-requirements.yml` file, and the README lists
these requirements and instructions.  However, these are only
required for github and Galaxy users, and not for users who
use the packaged roles, where it is confusing to see instructions
about installing requirements when none are needed.  We need to
make it …
> docs: remove unused Dependencies section in README

- tasks/insights-client.yml
- tests/tasks/get_insights_tags.yml
- tests/tests_insights_tags.yml
- vars/main.yml
The file with the tags of insights-client is
`/etc/insights-client/tags.yaml`, not `tags.yml`.
To ease the situation a bit, move the full path to a role variable.
Reported-by: Benjamin Blasco <bblasco@redhat.com>
> fix: fix filename with insights-client tags

- meta/collection-requirements.yml
This version contains a number of features and fixes that greatly help this role; while the role was able so far to work with older versions, let's require a recent version so it is possible to drop workarounds.
The upper version limit is unfortunately still needed for now.
> build: require community.general 6.2.0

- tasks/subscription-manager.yml
The `redhat_subscription` used to handle certain options both writing them to the config file (using `subscription-manager config`), and passing them as command line parameters to `subscription-manager register`. This was problematic for `rhsm_baseurl`, as subscription-manager sadly forces `https` as scheme when parsing `--baseurl` as passed to `register`. This was fixed with [1] (backported to community.general 6.x with [2]), available since community.general 6.1.0.
Hence, directly pass the `rhc_baseurl` role parameter as `rhsm_baseurl` parameter of the `redhat_subscription` module.
[1] https://github.com/ansible-collections/community.general/pull/5583
[2] https://github.com/ansible-collections/community.general/pull/5626
> refactor: pass rhc_baseurl directly to redhat_subscription

- README.md
- tasks/subscription-manager.yml
- tests/README.md
- tests/files/candlepin_data.yml
- tests/tests_proxy.yml
Starting with community.general 6.2.0, the `redhat_subscription` module has a `server_proxy_scheme` parameter to configure the type of proxy server that subscription-manager uses (see [1], backported to community.general 6.x with [2]).
Hence, add a `scheme` attribute for the `rhc_proxy` role parameter, allowing users to configure the proxy type. To make sure to be able to test this, also add new optional test variables, using them in "tests_proxy" if specified.
[1] https://github.com/ansible-collections/community.general/pull/5662
[2] https://github.com/ansible-collections/community.general/pull/5671
> feat: implement rhc_proxy.scheme

- meta/collection-requirements.yml
The issues in the `redhat_subscription` module shipped in the `community.general` collection were fixed in version 6.6.0, so it should not have regressions now.
Hence, stop pinning the `community.general` collection.
This reverts commit 26c0f43571306938de8be5571f9a7ec6512a7bb6.
> chore(meta): stop pinning community.general collection

- meta/collection-requirements.yml
This version contains a number of features and fixes that greatly help this role; while the role was able so far to work with older versions, let's require a recent version so it is possible to drop workarounds.
In particular, we need to require 6.6.0 so we can adapt to the new behaviour of rhsm_release [1], needed to run with ansible-core 2.15.
[1] https://github.com/ansible-collections/community.general/pull/6401
> build: require community.general 6.6.0

- tasks/subscription-manager.yml
The way the new version of rhsm_release works is - if the `release`
parameter is present, set the release to the given value.
If there is no `release` parameter, unset the release.
If the user does not set `rhc_release`, then it will be `null`,
and calling the rhsm_release module will be skipped.
See https://github.com/ansible-collections/community.general/pull/6401
for details.
Signed-off-by: Rich Megginson <rmeggins@redhat.com>
> fix: correctly set release using new behavior of rhsm_release

- tasks/subscription-manager.yml
- vars/main.yml
The `redhat_subscription` module used to always require credentials when `state=present`; since we used the module also to do basic configuration of `subscription-manager`, this required us to pass fake credentials (unused) when the system was already registered. This behaviour was changed with [1] (backported to `community.general` 6.x with [2]), and available since `community.general` 6.5.0.
Hence, drop the concept of fake credential, and pass `username` and `password` only when specified; `redhat_subscription` still properly checks that only one credential type is specified.
[1] https://github.com/ansible-collections/community.general/pull/5664
[2] https://github.com/ansible-collections/community.general/pull/6222
> refactor: drop fake credential workaround

- README.md
- tasks/insights-client.yml
- tests/tests_insights_remediation.yml
- vars/main.yml
The rhc-worker-playbook package, needed for the remediation support, is available in RHEL only starting from 8.4 (including 9); hence, do not attempt to setup remediation on older RHEL versions.
> fix: enable remediation only on RHEL >= 8.4

- tests/tests_environments.yml
Since we know which version can list the environments, specify that.
Fixes this test when run with RHEL 8 < 8.6.
> tests: tests_environments: fix distro version check

- tasks/subscription-manager.yml
rhc_organization and rhc_baseurl have "null" as default specified for them in defaults/main.yml, which means that the "d()" filter will never be used. Instead, check that they are non-null and non-omit, and use them only in that case.
Fixes commit b95a84e621bd98a74a5c57d5b76077895a7f71a0
Fixes #126
https://bugzilla.redhat.com/show_bug.cgi?id=2227821
https://bugzilla.redhat.com/show_bug.cgi?id=2227823
> fix: use rhc_organization and rhc_baseurl only when specified

- .ansible-lint
- .ostree/README.md
- .ostree/get_ostree_data.sh
- .ostree/packages-runtime.txt
- .ostree/packages-testing.txt
- .ostree/roles-testing.txt
- .sanity-ansible-ignore-2.12.txt
- .sanity-ansible-ignore-2.13.txt
- .sanity-ansible-ignore-2.14.txt
- .sanity-ansible-ignore-2.15.txt
- .sanity-ansible-ignore-2.9.txt
- README-ostree.md
- README.md
- meta/collection-requirements.yml
- tasks/set_vars.yml
- tests/tasks/setup_test_data.yml
Feature: Allow running and testing the role with ostree managed nodes.
Reason: We have users who want to use the role to manage ostree
systems.
Result: Users can use the role to manage ostree managed nodes.
Signed-off-by: Rich Megginson <rmeggins@redhat.com>
> feat: support for ostree systems

- .ansible-lint
- .ostree/get_ostree_data.sh
- meta/collection-requirements.yml
- tasks/insights-client.yml
- tasks/set_vars.yml
- tasks/subscription-manager.yml
- tests/tasks/setup_candlepin.yml
- tests/tasks/setup_squid.yml
- tests/tasks/setup_test_data.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
> refactor: improve support for ostree systems

- tests/tasks/setup_candlepin.yml
It seems that the `podman_container` thinks that the container is changed, in case it is already running, and thus it tries to recreate it; this might be an already reported issue [1].
To avoid problems on this, force the creation of the container to a new one, in case it is running already. This also gives back a new clean Candlepin.
[1] https://github.com/containers/ansible-podman-collections/issues/532
> tests: force recreating Candlepin container

- tests/tasks/setup_candlepin.yml
It seems the `podman_container` module cannot properly stop the running container when being asked using `recreate=true`; hence, do it manually before starting the new container.
This also reverts commit 12c1a38bd914547986509dbd1b9c955bc0f838f9, which is no more needed now.
> tests: manually stop the Candlepin container

- meta/main.yml
Enhancement:
After yet another internal discussion, re-enable the support for EL7; no other changes are needed in the role.
Issue Tracker Tickets (Jira or BZ if any):
https://issues.redhat.com/browse/RHEL-16976
https://issues.redhat.com/browse/RHEL-16977
> feat: support again EL7

- .ansible-lint
- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
The old ansible-community ansible-lint is deprecated.  There is a
new ansible-lint github action.
The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to convert the role to collection format before running
ansible-test.
This also requires tox-lsr 3.2.1 - bump other actions to use 3.2.1
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
Signed-off-by: Rich Megginson <rmeggins@redhat.com>
> ci: Use supported ansible-lint action; run ansible-lint against the collection

- README.md
- defaults/main.yml
- tasks/insights-client-unregistration.yml
- tasks/insights-client.yml
- tests/tests_insights_ansible_host.yaml
Adds the ansible host name option for insights-client
into the rhc role. This adds  support for setting an
ansible host name in inventory during insights-client
registration and updating the current ansible host name
in inventory if the system is already registered.
**Changes:**
- Adds `ansible_host` parameter to insights client task to set/update/reset ansible host name in HBI.
- Adds tests for ansible host name configuration.
- Updates README with usage documentation for `ansible_host` parameter.
Signed-off-by: Jason Jerome <jajerome@redhat.com>
> feat: add ansible host parameter to insights configuration

- tests/tasks/setup_candlepin.yml
The current latest release (4.4.3) introduces a regression that breaks the support for environments in subscription-manager. Since:
- we are not testing subscription-manager here, rather the rhc role
- the issue is already known by the Candlepin developers, and hopefully to be fixed in the next version
hence pin the Candlepin container to the latest version before the regression, i.e. 4.4.2. This way, we can keep testing changes in the rhc role.
> tests: temporarily pin Candlepin to 4.4.2

- tests/tasks/setup_candlepin.yml
Candlepin 4.4.4 fixes the regression that prevented environments to be used in subscription-manager. Hence, revert the container pinning, and keep using the latest version available.
This reverts commit 5e1bdc483baa335edf044e324fcd09d67b643359.
> Revert "tests: temporarily pin Candlepin to 4.4.2"

- README.md
- defaults/main.yml
- tasks/insights-client-unregistration.yml
- tasks/insights-client.yml
- tests/tests_insights_display_name.yml
Enhancement:
A new _rhc_insights.display_name_ parameter.
Reason:
The display name is a value managed by Insights Client. It is visible in the Host-Based Inventory and is used as the main visible name in the UI to identify a host and search for it.
Result:
The new _rhc_insights.display_name_ parameter sets the display name of the host. This value is written to the Insights Client config file and also set directly by a `--display-name` command. When marked as absent or on unregistration, the value is removed from the config file.
Issue Tracker Tickets (Jira or BZ if any):
https://issues.redhat.com/browse/CCT-13
> feat: Add a display name parameter

- README.md
- tasks/insights-client.yml
- tests/tests_insights_ansible_host.yml
Enhancement:
Ignoring  _rhc.ansible_host_ if set to an empty string.
Reason:
The empty string value causes:
- the Ansible host name to be reset in the Inventory by `insights-client --ansible_host=`;
- a line `ansible_host=` to be put in the config file.
The former is a job of `{state: absent}`. An empty string should not cause such a desctructive operation. The latter is ignored by the Client and is equivatent to that line missing.
Result:
Consistently with a similar condition of the display_name parameter, an empty string ansible_host is treated as undefined. It’s the same behavior as with a null value.
Issue Tracker Tickets (Jira or BZ if any):
- https://issues.redhat.com/browse/CCT-398
> fix: Ignore ansible_host: ""

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 1.6.1
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
> docs(changelog): version 1.6.1 [citest skip]

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- .yamllint.yml
- tests/tasks/setup_candlepin.yml
- tests/tasks/setup_squid.yml
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

- tests/tasks/setup_candlepin.yml
The Candlepin URL used to query the owner (= organization) used in the tests when using the self-deployed Candlepin was wrong, using the username rather than the organization name. It works fine because the username and the organization name are currently the same.
Hence, to avoid issues in the future, properly use the organization name instead. To simplify the maintenance of that code, create a new helper fact with the Candlepin URL for the current owner.
There is no behaviour change in the tests.
> tests: factorize & fix URL for candlepin owner

- tests/collection-requirements.yml
- tests/tasks/setup_candlepin.yml
Using the `containers.podman` collection to handle `podman` is a nice idea, however what that collection supports now is becoming more strict than what this role supports. Case in point: `containers.podman` now requires Python 3.6+ for the managed nodes, which breaks the testing of EL 7.
This means that sadly the setup of a self-deployed Candlepin needs to run `podman` commands manually; use the proper parameters for `podman run` depending on the OS.
The gymnastics of checking the return code & stderr of `podman stop` are needed because the `--ignore` option (which would be ideal) was introduced in `podman` 1.7.0, and EL 7 has `podman` 1.6.4.
There is no behaviour change.
> tests: run podman directly instead of using containers.podman

- tests/files/candlepin_data.yml
- tests/tasks/setup_candlepin.yml
The role officially supports only SCA, so switch the test account used in the self-deployed Candlepin to an SCA-only account.
As consequence, also adapt the product certificate & repositories used to what the new account can access to.
There are no behaviour changes.
> tests: switch to an SCA account for Candlepin

- tasks/subscription-manager.yml
`auto_attach` is supposed to automatically attach subscriptions for accounts in entitlement mode. in Simple Content Access mode, this option becomes a no-op in subscription-manager.
The usage of this option was originally added to help testing regardless of the content access mode, even if the role supports only SCA. Since the entitlement mode has been officially deprecated for a couple of years already, and it is going away soon, then stop using the `auto_attach` option of the `redhat_subscription` module.
There is no behaviour change.
> fix: drop usage of "auto_attach" of the "redhat_subscription" module

- tests/tests_environments.yml
Simplify a distro check in `tests_environments.yml` to ease potentially adding more EL distros:
- because of the short-circuiting of expressions, all the "or" conditions are run currently only on "CentOS" and "RedHat"
- since CentOS Stream is the only "unversioned" EL distro, move its condition as the first after the distro check
- drop the name check, leaving only the version check, in any other case (i.e. currently on "RedHat")
This makes is possible to support more EL distros in this check, and in case they are versioned all it is needed is to tweak the first condition (i.e. the check for `ansible_distribution not in ...`).
There is no behaviour change.
> tests: simplify distro check in tests_environments.yml

- tests/tasks/setup_candlepin.yml
The Candlepin account used for tests uses SCA, and thus any activation key for it can already access to the whole content of the organization of the account. The addition of the pools to the activation key is thus redundant, and upcoming versions of Candlepin will not allow this behaviour anymore.
Hence, stop adding pools to the activation key, which is no more needed.
There is no behaviour change.
> tests: stop adding pools to the activation key

- .github/workflows/tft.yml
- plans/README-plans.md
- plans/test_playbooks_parallel.fmf
* Calculate number of managed nodes with this formula:
(( number_of_test_playbooks / 10 + 1 ))
* Add README explaining how to run the plan locally and remotely
> ci: Add test plan that runs CI tests and customize it for each role

- tests/tasks/setup_candlepin.yml
- tests/tasks/teardown_candlepin.yml
- tests/tests_environments.yml
- tests/tests_proxy.yml
- tests/tests_register_unregister.yml
- tests/tests_repositories.yml
Enhancement: In always block, import a task to cleanup candlepin container in tests that import the task tests/tasks/setup_candlepin.yml, which starts candlepin container.
Reason: Candlepin container remains after test playbook finishes. If you remove `container-selinux` rpm, you got selinux denials because the container is running but selinux policies for containers are removed.
> tests: Cleanup candlepin container
